 # Create image based on the official Node 6 image from the dockerhub
FROM hayd/alpine-deno:1.0.1

# RUN deno install --allow-read --allow-run --allow-write -f --unstable https://deno.land/x/denon/denon.ts

EXPOSE 4000 5432

# Create a directory where our app will be placed
RUN mkdir -p /usr/src/app

# Change directory so that our commands run inside this new directory
WORKDIR /usr/src/app

# Get all the code needed to run the app
COPY . /usr/src/app

RUN deno cache server.ts
